version: 1
profiles:
  default:
    description: "Run Python scraper and collect output files"
    docker:
      template: "python/Dockerfile.chromedriver"
    environment:
      PYTHONPATH: "/app/src"
    pre_run:
      - command: "sh"
        args: ["-c", "find . -name '.venv' -type d -exec rm -rf {} +"]
        cwd: "/app"
      - command: "sh"
        args: ["-c", "rm -rf /app/data/*"]
        cwd: "/app"
    execute:
      command: "python"
      args: ["scraper.py"]
      cwd: "src"
    artifacts:
      - path: "/app/data/**/*"  # For any data in /app/data
        target: "/results"
